# Generated by Django 4.0 on 2021-12-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'FA'), ('Sport', 'SP'), ('Toys', 'TO'), ('Electronic', 'EL'), ('Home', 'HO')], default='FA', max_length=15),
        ),
    ]
