# Generated by Django 4.0 on 2021-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Sport', 'Sport'), ('Toys', 'Toys'), ('Electronic', 'Electronic'), ('Home', 'Home')], default='Fashion', max_length=15),
        ),
    ]
