# Generated by Django 4.0 on 2021-12-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_date_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
